### ISSUE TITLE
Race condition with TThreadedQueue usage

### ISSUE THREAD

**Issue by Fulgan** [danieleteti/loggerpro#23] opened 2018-08-06 07:13 UTC
After struggling for several weeks with random "Runtime error 217" appearing at program termination, we have found out that there is most probably a race condition with the use of TThreadQueue.

Our applications creates two log writer instances. These writers are mostly used during program startup. When leaving the application running with no special interaction (i.e. overnight on a locked desktop), it almost always end up with all the loggerpro threads (TLoggerThread and TAppenderThread) consuming all available CPU. At this point, closing the application will result in a runtime error 217 (which basically is an exception happening when system.SysUtils.pas finalization clause has alread been executed and the exception handling system terminated).

Trace captured with madExcept while the process is pegging the CPU but before termination shows that they are all locked in TMonitor.Wait: 3 of them stopped on "ResetEvent" and the last one (random) on "NewWaitObject".

The capture was performed on several occasions and with several different cases of hung process and they all look exactly the same. Trace perfromed while the process isn't using all available CPU do not exhibit that same pattern (threads are on "WaitForSingleObjects")

[madTraceProcess_wineur_race_condition.zip](https://github.com/danieleteti/loggerpro/files/2261481/madTraceProcess_wineur_race_condition.zip)

**Comment by pjrobin** [comment] 2018-08-06 11:57
[bugreport.txt](https://github.com/danieleteti/loggerpro/files/2262414/bugreport.txt)
Seems to be the same problem here

**Comment by Fulgan** [comment] 2018-08-06 12:14
@pjrobin I don't think so (at least, not in this dump). In your case, all LoggerPro threads are on WaitForSingleObjectEx (which should be their default state when not directly handling messages) but you have an AV in the main thread, possibly because you've freed the application main form already but still have some code posted to the queue using TThread.Queue

**Comment by pjrobin** [comment] 2018-08-06 13:02
@Fulgan OK, thanks!

**Comment by danieleteti** [comment] 2018-08-06 17:12
@Fulgan can you provide a small example which reproduce the behaviour? LoggerPro is used in hundreds of thousands (literally) H24 servers with no problems. Can you provide more info about the running environment?

**Comment by krularkru** [comment] 2018-08-06 23:35
We too have experienced similar problems as @Fulgan describes. We use LoggerPro in a Windows Service application compiled with Delphi XE3 running on a Windows 2016 Server. After an average running of 20days some of the LoggerPro threads (TLoggerThread and TAppenderThread couples) start racing and the overall CPU usage surges to 100%. Unfortunatly we cannot reproduce the behaviour ourselves.

**Comment by Fulgan** [comment] 2018-08-07 08:15
In this case, loggerpro is used in a GUI application (accounting). It is used to send telemetry data to a message queue system when running in a hosted environment but, in this case, that functionality is not used and the corresponding appender isn't created. This means that aside from a coupe of messages during startup, no message is logged.

There is two nearly identical loggers created at the same time: one for general purpose messages and one for GRDP-related messages and a controller object will queue a message to one pipeline or the other depending on it's nature.

In my case, there is only one appender active: it's a custom file appender that is able to share a log file with other application instances (the same log file is used by several instances running on different machines). I have tried disabling this appender in the past and verified that this didn't solve the issue.

The compiler is Delphi 10.2.3 with the latest RTL patch. the application is a VCL, mostly single-threaded application.

In the specific case described, I started the application on my machine, minimized it and, except a couple of times when i restored the main window and minimized it again, it was unused. I kept monitoring it using ProceyssExplorer during the day.

When I saw the application consuming all CPU, I used madTraceProcess to gather the stack trace I attached to the report. I also verified that the IDs of the threads that were clearly consuming all CPU were the two logger and appender threads.

I will try to reproduce the issue with a simpler demo app but since it only after leaving the application running for several hours (and since I'm going in holiday tonight) I might not be able to report back immediately.

**Comment by Fulgan** [comment] 2018-08-07 09:31
I was able to produce a demo project that can reproduce the issue. You can get it from my repo there: https://github.com/Fulgan/LoggerProIssueDemo

To encounter the bug, set the number of loggers to 5 or 10 and start them (the more you have, the quicker you'll encounter the issue but the harder it'll be to recover when it occurs). After this, leave the application running for some time. With 10 loggers, it took about 90 minute for the problem to show up on my machine.

My take o why you're not seeing this in your code is that you're using a single logger instance: due to the (weird and convoluted) way TThreadedQueue and TMonitor works, you will need more that one instance of a TThreadedQueue in your application to encounter the issue. I think that as long as you have only one queue, you'll avoid the problem.

This looks like a RTL issue with TMonitor and TThreadedQueue. Beside getting EMB to fix it, the safest path would be to reimplement the shared queue (or perhaps use OmniThread as a replacement)

**Comment by krularkru** [comment] 2018-08-07 15:14
I found some links that strengthen @Fulgan 's theory regarding possible bug in TThreadedQueue and TMonitor:

- **Embarcadero Forums:** _Probable issue in TThreadedQueue (due to TMonitor) under Delphi Tokyo_ [https://forums.embarcadero.com/thread.jspa?messageID=941762](url)
- **Embarcadero QC:** _TThreadedQueue - should wait INFINITE but doesn't do it_ [https://quality.embarcadero.com/browse/RSP-19993](url)

**Comment by danieleteti** [comment] 2018-08-09 11:04
I saw the bug report. Guys, do you have some direct esperience with a good and fast thread safe queue (working on all supported platforms)?

I have wrote some code which simply serialize access in a TQueue<T> but I'd like ti avoid customers implementations forum such kind of so general things.

**Comment by Fulgan** [comment] 2018-08-09 11:58
OmniThread has a robust MT queue implementation but I admit my experience with it is limited: it worked (rather well) for what I used it but I have no idea how the performance relates to what you need for LoggerPro.

My suggestion would be to write a small abstraction for the queue and inject the instance: that will allow for different implementations to be used. 

When I get back, I can write that code and also a TOmiQueue implementation and submit it as a pull request.

**Comment by danieleteti** [comment] 2018-08-10 11:01
I'm working on a custom `TThreadQueue<T>`. I've already replaced all the occurrence into the LoggerPro Core and I'm doing some stress test using (also) the sample program sent by @Fulgan .

As soon as I've a beta version I'll provide to you to do tests. It is a very core change and I don't want to loose the LoggerPro stability, so we have to do a lot of testing.

Have fun

**Comment by danieleteti** [comment] 2018-08-10 15:55
In the new feature branch `https://github.com/danieleteti/loggerpro/tree/feature_newthreadedqueue` there is the beta version. PLease test it with your real cases. All the unit tests and all the samples are OK but we need real test case too. The sample sent by @Fulgan also runs OK with this version.

**Comment by danieleteti** [comment] 2018-08-11 15:01
[This commit](https://github.com/danieleteti/loggerpro/commit/a0e0515fa1408558783b3982d21101cb3016337a) fixes a nasty bug in the `TThreadSafeQueue<T>` which affects the logger.

**Comment by krularkru** [comment] 2018-08-14 06:34
I am now testing the beta fix. So far it looks promising. My personal condition of satisfaction is that the application runs uninterrupted 24/7 for 30days. I'll keep you posted. Many thanks @Fulgan for pin-pointing the problem and @danieleteti for promptly addressing the issue. What a great library you have provided the community!

**Comment by Fulgan** [comment] 2018-08-20 08:29
I'm back at the office today so I need a bit more time for testing with out real app. Preliminary tests seems OK, though

**Comment by Fulgan** [comment] 2018-08-27 06:12
As of today, I have had no report of any problem with the new queue and I see no trace of lost log items.

I think it's a success.

**Comment by krularkru** [comment] 2018-08-27 15:05
So far so good. My condition of satisfaction is that the application runs uninterrupted 24/7 for 30days. So 14 September I hope to celebrate '-)

**Comment by danieleteti** [comment] 2018-08-27 16:00
OK, so I think that we could do the merge with the master branch and propose a 1.3 beta version so that everyone can test this new version in testing environments. I'll do it within this week.

**Comment by krularkru** [comment] 2018-09-16 23:08
@danieleteti your fix has been stable now for over a month on the system we've tested on. Many thanks for yours and @Fulgan's input!

**Comment by danieleteti** [comment] 2018-09-17 17:21
Perfect! We'll release 1.3.0 ASAP.

Thank you guys

**Closed by danieleteti** 2018-09-17 17:21 UTC
Labels: accepted, bug

**Comment by edwinyzh** [comment] 2018-09-18 02:15
@danieleteti , with Commits on Aug 18, 2018, under XE4 I couldn't reproduce the issue using @Fulgan's LoggerProIssueDemo. [TThreadedQueue and TMonitor seem to had issues](https://www.thedelphigeek.com/2011/05/tmonitor-bug.html) and I thought it's been fixed in all newer versions...

**Comment by danieleteti** [comment] 2018-09-18 13:53
All the changes have been merged in the `master` with some other stuff included in the 1.3.0. You can switch on the master version and do the tests before the 1.3.0 will be released. If no bugs will be found, we'll release the current dev version as 1.3.0.
