### ISSUE TITLE
Only one backup file ever used

### ISSUE THREAD

**Issue by FixzoneBrian** [danieleteti/loggerpro#73] opened 2023-04-27 09:06 UTC
Found a problem with the backup files it is only ever using 1 backup file regardless of what you set the MaxBackupFileCount to 
In LoggerPro.FileAppender create it has
fMaxBackupFileCount:= Min(1, aMaxBackupFileCount);

**Comment by luebbe** [comment] 2023-04-29 11:05
Which version are you using? this is a duplicate of #61 and should already be fixed since a while.

**Comment by FixzoneBrian** [comment] 2023-05-03 08:13
It's version 1.4.3

**Closed** 2023-06-21 09:59 UTC
Labels: accepted
